api/urls.py
# api/urls.py

from django.urls import path
from . import views

# Namespace for the API app
app_name = 'api'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.PostListView.as_view(), name='post-list'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('comments/', views.CommentListCreateView.as_view(), name='comment-list'),
]

mitchs_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('posts/', views.PostListView.as_view(), name='post-list'),
    path(
        'posts/<int:year>/<int:month>/<int:day>/<slug:slug>/',
        views.PostDetailView.as_view(),
        name='post-detail',
    ),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('terms/', views.terms_and_conditions, name='terms-and-conditions'),
    path('topics/', views.TopicListView.as_view(), name='topic-list'),
    path('topics/<slug:slug>/', views.TopicDetailView.as_view(), name='topic-detail'),
    path('form-example/', views.form_example, name='form-example'),
    path('formview-example/', views.FormViewExample.as_view(), name='formview-example'),
    path('contact-form/', views.ContactFormView.as_view(), name='contact-form'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('photo_contest/', views.PhotoContestView.as_view(), name='photo-contest'),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# blog/models.py
"""
The blog app models.
"""

from django.conf import settings  # Imports Django's loaded settings
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

class PostQuerySet(models.QuerySet):
    """
    The Post Query Set Class
    """
    def published(self):
        return self.filter(status=self.model.PUBLISHED)

    def drafts(self):
        return self.filter(status=self.model.DRAFT)

    def get_authors(self):
        User = get_user_model()
        return User.objects.filter(blog_posts__in=self).distinct()

class Topic(models.Model):
    """
    The Topic Class
    """
    name = models.CharField(
        max_length=50,
        unique=True,  # No duplicates!
        null=False
    )
    slug = models.SlugField(unique=True, null=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('topic-detail',
            kwargs = {
               'slug': self.slug
            })

class Post(models.Model):
    """
    Represents a blog post
    """
    DRAFT = 'draft'
    PUBLISHED = 'published'
    STATUS_CHOICES = [
        (DRAFT, 'Draft'),
        (PUBLISHED, 'Published')
    ]
    title = models.CharField(max_length=255, null=False)
    banner = models.ImageField(
        blank=True,
        null=True,
        help_text='A banner image for the post'
    )
    content = RichTextUploadingField()
    created = models.DateTimeField(auto_now_add=True, null=True)  # Sets on create
    updated = models.DateTimeField(auto_now=True, null=True)  # Updates on each save
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,  # The Django auth user model
        on_delete=models.PROTECT,  # Prevent posts from being deleted
        related_name='blog_posts',  # "This" on the user model
        null=False
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default=DRAFT,
        help_text='Set to "published" to make this post publicly visible',
        null=False
    )
    published = models.DateTimeField(
        null=True,
        blank=True,
        help_text='The date & time this article was published',
    )
    slug = models.SlugField(
        null=False,
        unique_for_date='published',
    )
    topics = models.ManyToManyField(
        Topic,
        related_name='blog_posts'
    )
    objects = PostQuerySet.as_manager()

    class Meta:
        # Sort by the `created` field. The `-` prefix
        # specifies to order in descending/reverse order.
        # Otherwise, it will be in ascending order.
        ordering = ['-created']

    def publish(self):
        self.status = self.PUBLISHED
        self.published = timezone.now()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        if self.published:
            kwargs = {
                'year': self.published.year,
                'month': self.published.month,
                'day': self.published.day,
                'slug': self.slug
            }
        else:
            kwargs = {'pk': self.pk}

        return reverse('post-detail', kwargs=kwargs)

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    text = models.TextField()
    approved = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return f'Comment {self.text} by {self.name} dated {self.created}'

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()
    submitted = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-submitted']

    def __str__(self):
        return f'{self.submitted.date()}: {self.email}'

class PhotoContest(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    photo = models.ImageField(upload_to='uploads/photo_contest/', null=False)
    submitted = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-submitted']

    def __str__(self):
        return f'{self.submitted.date()}: {self.email}'

blog/forms.py
# blog/forms.py

from django import forms
from . import models

class NameForm(forms.Form):
    first_name = forms.CharField(label='First name', max_length=50)
    last_name = forms.CharField(label='Last name', max_length=50)

class ExampleSignupForm(forms.Form):
    first_name = forms.CharField(label='First name', max_length=50)
    last_name = forms.CharField(label='Last name', max_length=50)
    email = forms.EmailField()
    gender = forms.ChoiceField(
        label='Gender',
        required=False,
        choices=[
            (None, '-------'),
            ('m', 'Male'),
            ('f', 'Female'),
            ('n', 'Non-binary'),
        ]
    )
    receive_newsletter = forms.BooleanField(
        required=False,
        label='Do you wish to receive our newsletter?'
    )

class PhotoContestForm(forms.Form):
    first_name = forms.CharField(label='First name', max_length=50)
    last_name = forms.CharField(label='Last name', max_length=50)
    email = forms.EmailField()
    photo = forms.ImageField()

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = [
            'post',
            'name',
            'email',
            'text',
        ]
        labels = {
            'text': 'Comment'
        }
        widgets = {
            'post': forms.HiddenInput()
        }

blog/views.py
# blog/views.py
"""
The blog app views.
"""
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import DetailView, FormView, ListView, CreateView
from django.urls import reverse_lazy
from django.contrib import messages
from . import forms, models

class HomeView(TemplateView):
    """
    The Home View Class Template View.
    """
    template_name = 'blog/home.html'

class AboutView(TemplateView):
    """
    The About View Class Template View.
    """
    template_name = 'blog/about.html'

class PostListView(ListView):
    """
    The Post List View.
    """
    model = models.Post
    context_object_name = 'posts'
    queryset = models.Post.objects.published().order_by('-published')

class PostDetailView(DetailView):
    """
    The Post Detail View.
    """
    model = models.Post

    def get_queryset(self):
        queryset = super().get_queryset().published()

        # If this is a `pk` lookup, use default queryset
        if 'pk' in self.kwargs:
            return queryset

        # Otherwise, filter on the published date
        return queryset.filter(
            published__year=self.kwargs['year'],
            published__month=self.kwargs['month'],
            published__day=self.kwargs['day'],
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Get the post object
        post = self.get_object()

        # Set the post field on the form
        comment_form = forms.CommentForm(initial={'post': post})
        comments = models.Comment.objects.filter(post=post)

        context['comment_form'] = comment_form
        context['comments'] = comments.order_by('-created')

        return context

class TopicListView(ListView):
    """
    The Topic List View.
    """
    model = models.Topic
    context_object_name = 'topics/'
    queryset = models.Topic.objects.all()

class TopicDetailView(DetailView):
    """
    The Topic Detail View.
    """
    model = models.Topic

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['topics_posts'] = models.Post.objects.filter(\
            topics__slug=self.kwargs['slug']).published().order_by('-published')

        return context

def terms_and_conditions(request):
    """
    The Terms and Conditions request function.
    """
    return render(request, 'blog/terms_and_conditions.html')

class ContactView(TemplateView):
    """
    The Contact View Class Template View.
    """
    template_name = 'blog/contact.html'

class FormViewExample(FormView):
    template_name = 'blog/form_example.html'
    form_class = forms.ExampleSignupForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        # Create a "success" message
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Thank you for signing up!'
        )
        # Continue with default behaviour
        return super().form_valid(form)

def form_example(request):
    # Handle the POST
    if request.method == 'POST':
        # Pass the POST data into a new form instance for validation
        form = forms.ExampleSignupForm(request.POST)

        # If the form is valid, return a different template.
        if form.is_valid():
            # form.cleaned_data is a dict with valid form data
            cleaned_data = form.cleaned_data

            return render(
                request,
                'blog/form_example_success.html',
                context={'data': cleaned_data}
            )
    # If not a POST, return a blank form
    else:
        form = forms.ExampleSignupForm()

    # Return if either an invalid POST or a GET
    return render(request, 'blog/form_example.html', context={'form': form})

class ContactFormView(CreateView):
    model = models.Contact
    success_url = reverse_lazy('home')
    fields = [
        'first_name',
        'last_name',
        'email',
        'message',
    ]

    def form_valid(self, form):
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Thank you! Your message has been sent.'
        )
        return super().form_valid(form)

class PhotoContestView(CreateView):
    template_name = 'blog/photo_contest_form.html'
    model = models.PhotoContest
    success_url = reverse_lazy('home')
    fields = [
        'first_name',
        'last_name',
        'email',
        'photo',
    ]

    def form_valid(self, form):
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Thank you for your submission! Good Luck!'
        )
        return super().form_valid(form)

blog/templates/blog/about.html
<!-- blog/templates/blog/home.html -->

{% extends "blog/base.html" %}
{% block page_title %}About Me{% endblock %}
{% block main %}
{% load static %}
<h2>About Me</h2>
<p id="about_me"><img src='{% static "blog/mitchell.jpg" %}' alt="Mitchell Burr" id="photo_me"><br/>
Welcome to my blog that is just getting started. I am Mitchell, a DevOps Engineer, who is focused a
lot on automation and operational improvements for my company. I am currently learning Python to
expand my knowledge in the development space, so I can further take advantage of automation tools
that we use, like Ansible, that are based on the language.</p>
<p id="about_me">Here is a great example of how I am progressing through my Advanced Python course,
using the Django web framework to build out this custom blog website.</p>
{% endblock %}

blog/templates/blog/base.html
<!-- blog/templates/blog/base.html -->
{% load static %} <link rel="stylesheet" href="{% static "blog/base.css" %}">
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Mitchell's Site – {% block page_title %}An okay blog{% endblock %}</title>
  <link href="//fonts.googleapis.com/css?family=Caveat&subset=latin,latin-ext" rel="stylesheet" type="text/css">
</head>

<body>
  {% if messages %}
  <div class="django-messages">
    {% for message in messages %}
    <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
  </div>
  {% endif %}
  <!-- The header -->
  <header id="site-header">
     <h1><img src="{% static "blog/jason.png" %}" alt="Logo" id="logo">Mitchell's Blog</h1>
     <p>Your daily dose of great stuff!</p>
     <!-- Top navigation -->
     <nav id="top-nav">
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="{% url "about" %}">About</a></li>
        <li><a href="{% url "post-list" %}">Posts</a></li>
        <li><a href="{% url "topic-list" %}">Topics</a></li>
        <li><a href="{% url "photo-contest" %}">Photo Contest</a></li>
        <li><a href="{% url "contact-form" %}">Contact</a></li>
      </ul>
    </nav>
  </header>
  <div id="alt-body">
  <main id="main-content">

  <div>
   {% block main %}
   <!-- Content for the main block will be rendered here -->
   {% endblock %}
  </div>
  <div id="sidebars">
    <aside id="sidebar">
      <section>
        <div class="box-header">
        <h3>Top Topics</h3>
        </div>
        <ul>
          {% for topic in top_topics %}
            <li><a href="{{ topic.get_absolute_url }}">{{ topic.name }}</a> ({{ topic.post_count }})</li>
          {% endfor %}
        <br/>
        <a href="{% url "topic-list" %}">View All</a>
        </ul>
      </section>
    </aside>
         <br />
     <aside id="sidebar">
       <section id="author-list">
         <div class="box-header">
         <h3>Authors</h3>
         </div>
         <ul>
           {% for author in authors %}
             <li>{{ author.first_name }}</li>
           {% endfor %}
         </ul>
       </section>
     </aside>


   </div>
  </main>

  <!-- The footer -->
  <footer id="site-footer">
    <!-- Print copyright with the current year -->
    Copyright &copy; 1986 - {% now 'Y' %} by Mitchell Burr Inc.
    All Rights Reserved
    <br/>
    <a href="{% url "terms-and-conditions" %}">Terms & Conditions</a>
  </footer>
</div> <!-- End alt-body div -->
<script src="{% static "blog/comments.js" %}"></script>
</body>
</html>

blog/templates/blog/comment_form.html
{# blog/templates/blog/comment_form.html #}

<form action="{% url "api:comment-list" %}" method="post" id="comment-form">
  {% csrf_token %}
  <table class="form-table">
    {{ form.as_table }}
    <tr>
      <td></td>
      <td><button type="submit" class="btn-primary">Send</button></td>
    </tr>
  </table>
</form>

blog/templates/blog/contact.html
<!-- blog/templates/blog/home.html -->

{% extends "blog/base.html" %}
{% block page_title %}Contact Me{% endblock %}
{% block main %}
<div class="container">
<h2>Contact Me</h2>

  <form action="#">
    <label for="fname">First Name</label>
    <input type="text" id="fname" name="firstname" placeholder="Your name...">
    <br/><br/>
    <label for="lname">Last Name</label>
    <input type="text" id="lname" name="lastname" placeholder="Your last name...">
    <br/><br/>
    <label for="subject">Subject</label>
    <input type="text" id="subject" name="subject" placeholder="Subject...">
    <br/><br/>
    <label for="message">Message</label>
    <textarea id="message" name="message" placeholder="Type your message here..." style="height:200px"></textarea>

    <input type="submit" value="Submit">
  </form>
</div>

{% endblock %}

blog/templates/blog/contact_form.html
{# blog/templates/blog/contact_form.html #}

{% extends "blog/base.html" %}

{% block page_title %}Contact{% endblock %}


{% block main %}

<form method="post">
  {% csrf_token %}
  <table class="form-table">
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn-primary">Submit</button>
</form>
{% endblock %}

blog/templates/blog/form_example.html
{# blog/templates/blog/form_example.html #}

{% extends "blog/base.html" %}

{% block main %}
<h1>Form example</h1>
<form action="" method="post" novalidate>
  {% csrf_token %}
<table class="form-table">
{{ form.as_table }}
<tr>
  <td colspan=2>
    <button type="submit" class="btn-primary">Sign up!</button>
  </td>
</tr>
</table>
</form>
{% endblock %}

blog/templates/blog/form_example_success.html
{# blog/templates/blog/form_example_success.html #}
{% extends "blog/base.html" %}

{% block main %}
Thank you, {{ data.first_name }}!

<p>This is the data received from the form: </p>
<pre>{{ data|pprint }}</pre>

{% endblock %}

blog/templates/blog/home.html
<!-- blog/templates/blog/home.html -->

{% extends "blog/base.html" %}
{% block page_title %}My Homepage{% endblock %}
{% block main %}
<p>Welcome to the home page of my blog!</p>
<h2>Latest posts</h2>
{% for post in latest_posts %}
{% include "blog/post_preview.html" %}
{% endfor %}

{% endblock %}

blog/templates/blog/post_detail.html
<!-- blog/templates/blog/post_detail.html -->

{% extends "blog/base.html" %}
{% block page_title %}{{ post.title }}{% endblock %}
{% block main %}
<article id="post-detail-article">
  <h1>{{ post.title }}</h1>
   <span class="published"><time>Published {{ post.published|timesince }} ago</time></span><br/>
   <span class="author">by {{ post.author.get_full_name }}</span>
   <br/>
   {% for topics in post.topics.all %}
      {%spaceless%}
      <span class="topic-link"><a href="{{ topics.get_absolute_url }}">{{ topics.name }}</a>{%if not forloop.last%},{%endif%}</span>
      {%endspaceless%}
   {% endfor %}
   {% if post.banner %}
    <br /><br />
    <img src="{{ post.banner.url }}" width="90%" alt="Banner image">
   {% endif %}
   <section class="content">{{ post.content|safe|linebreaks }}</section>

</article>

<section class="comments">
   {% if comments %}
     <h3>Latest comments</h3>
     {% for comment in comments %}
       <div class="comment">
         <span class="by-line">By {{ comment.name }} | <time>{{ comment.created }}</time></span>
         {{ comment.text|linebreaks }}
       </div>
     {% endfor %}
   {% endif %}
 
   <h3>Leave a comment</h3>
   {# Alias the variable for the included template #}
   {% with form=comment_form %}
     {% include "blog/comment_form.html" %}
   {% endwith %}
 </section>
{% endblock %}

blog/templates/blog/post_list.html
<!-- blog/templates/blog/home.html -->

{% extends "blog/base.html" %}
{% block page_title %}Posts{% endblock %}
{% block main %}
<h2>Blog posts</h2>

{% for post in posts %}
{% include "blog/post_preview.html" %}
{% endfor %}
{% endblock %}

blog/templates/blog/post_preview.html
<article class="post-preview">
 <div class="box-header">
 <h3>{{ post.title }}</h3>
 </div>
  <br/>
  <time>| {{ post.published|timesince }} ago</time>
  <br/>
  <section class="teaser">
    {{ post.content|striptags|truncatewords:20 }}
    <br/><br/>
    <p><a href="{{ post.get_absolute_url }}" class="btn-primary">Read More &rarr;</a></p>
  </section>
 </article>
<br/>

blog/templates/blog/terms_and_conditions.html
{# blog/templates/blog/terms_and_conditions.html #}

{% extends "blog/base.html" %}

{% block page_title %}Terms & Conditions{% endblock %}

{% block main %}
<h3>Terms and Conditions</h3>
<p>Last updated: November 02, 2022</p>
<p>Please read these terms and conditions carefully before using Our Service.</p>
<h3>Interpretation and Definitions</h3>
<h4>Interpretation</h4>
<p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
<h4>Definitions</h4>
<p>For the purposes of these Terms and Conditions:</p>
<ul>
<li>
<p><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
</li>
<li>
<p><strong>Country</strong> refers to: Ontario,  Canada</p>
</li>
<li>
<p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Mitchell's Blog.</p>
</li>
<li>
<p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
</li>
<li>
<p><strong>Service</strong> refers to the Website.</p>
</li>
<li>
<p><strong>Terms and Conditions</strong> (also referred as &quot;Terms&quot;) mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service. This Terms and Conditions agreement has been created with the help of the <a href="https://www.privacypolicies.com/terms-conditions-generator/" target="_blank">Terms and Conditions Generator</a>.</p>
</li>
<li>
<p><strong>Third-party Social Media Service</strong> means any services or content (including data, information, products or services) provided by a third-party that may be displayed, included or made available by the Service.</p>
</li>
<li>
<p><strong>Website</strong> refers to Mitchell's Blog, accessible from <a href="www.mitchellsblog.com" rel="external nofollow noopener" target="_blank">www.mitchellsblog.com</a></p>
</li>
<li>
<p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
</li>
</ul>
<h3>Acknowledgment</h3>
<p>These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.</p>
<p>Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.</p>
<p>By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service.</p>
<p>You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service.</p>
<p>Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before using Our Service.</p>
<h3>Links to Other Websites</h3>
<p>Our Service may contain links to third-party web sites or services that are not owned or controlled by the Company.</p>
<p>The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>
<p>We strongly advise You to read the terms and conditions and privacy policies of any third-party web sites or services that You visit.</p>
<h3>Termination</h3>
<p>We may terminate or suspend Your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.</p>
<p>Upon termination, Your right to use the Service will cease immediately.</p>
<h3>Limitation of Liability</h3>
<p>Notwithstanding any damages that You might incur, the entire liability of the Company and any of its suppliers under any provision of this Terms and Your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by You through the Service or 100 USD if You haven't purchased anything through the Service.</p>
<p>To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, loss of data or other information, for business interruption, for personal injury, loss of privacy arising out of or in any way related to the use of or inability to use the Service, third-party software and/or third-party hardware used with the Service, or otherwise in connection with any provision of this Terms), even if the Company or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.</p>
<p>Some states do not allow the exclusion of implied warranties or limitation of liability for incidental or consequential damages, which means that some of the above limitations may not apply. In these states, each party's liability will be limited to the greatest extent permitted by law.</p>
<h3>&quot;AS IS&quot; and &quot;AS AVAILABLE&quot; Disclaimer</h3>
<p>The Service is provided to You &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its own behalf and on behalf of its Affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, the Company provides no warranty or undertaking, and makes no representation of any kind that the Service will meet Your requirements, achieve any intended results, be compatible or work with any other software, applications, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.</p>
<p>Without limiting the foregoing, neither the Company nor any of the company's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Service, or the information, content, and materials or products included thereon; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Service; or (iv) that the Service, its servers, the content, or e-mails sent from or on behalf of the Company are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.</p>
<p>Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to You. But in such a case the exclusions and limitations set forth in this section shall be applied to the greatest extent enforceable under applicable law.</p>
<h3>Governing Law</h3>
<p>The laws of the Country, excluding its conflicts of law rules, shall govern this Terms and Your use of the Service. Your use of the Application may also be subject to other local, state, national, or international laws.</p>
<h3>Disputes Resolution</h3>
<p>If You have any concern or dispute about the Service, You agree to first try to resolve the dispute informally by contacting the Company.</p>
<h3>For European Union (EU) Users</h3>
<p>If You are a European Union consumer, you will benefit from any mandatory provisions of the law of the country in which you are resident in.</p>
<h3>United States Legal Compliance</h3>
<p>You represent and warrant that (i) You are not located in a country that is subject to the United States government embargo, or that has been designated by the United States government as a &quot;terrorist supporting&quot; country, and (ii) You are not listed on any United States government list of prohibited or restricted parties.</p>
<h3>Severability and Waiver</h3>
<h4>Severability</h4>
<p>If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</p>
<h4>Waiver</h4>
<p>Except as provided herein, the failure to exercise a right or to require performance of an obligation under these Terms shall not effect a party's ability to exercise such right or require such performance at any time thereafter nor shall the waiver of a breach constitute a waiver of any subsequent breach.</p>
<h3>Translation Interpretation</h3>
<p>These Terms and Conditions may have been translated if We have made them available to You on our Service.
You agree that the original English text shall prevail in the case of a dispute.</p>
<h3>Changes to These Terms and Conditions</h3>
<p>We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. If a revision is material We will make reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at Our sole discretion.</p>
<p>By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, in whole or in part, please stop using the website and the Service.</p>
<h3>Contact Us</h3>
<p>If you have any questions about these Terms and Conditions, You can contact us:</p>
<ul>
<li>By email: mitchell@myblog.com</li>
</ul>
{% endblock %}